import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ToggleLang from '../../components/ToggleLang';
import "../globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params: { lang: string }
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToggleLang lang={params.lang}/>
        {children}
      </body>
    </html>
  )
}
